import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/layout";
import { Box, Button, HStack, Icon, Stack, Text } from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { User } from "@/models/User";
import { MdShoppingCart, MdLogout } from "react-icons/md";
import { MenuLogged } from "@/components/menu-logged";
import { ProductList } from "@/data/products";
import { CardProduct } from "@/components/card-product";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [user, setUser] = useState<User>({
    id: "",
    password: "",
    username: "",
  });

  useEffect(() => {
    const userLogged = localStorage.getItem("ps-current-user");

    console.log(userLogged);

    if (userLogged) {
      const userDb = JSON.parse(userLogged) as User;

      setUser(userDb);
    }
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Layout>
          {user.username.length > 0 ? (
            <MenuLogged username={user.username} />
          ) : null}
          <Stack
            direction={"row"}
            flexWrap={"wrap"}
            gap={4}
            p={4}
            justifyContent={"center"}
          >
            {ProductList.map((item, index) => (
              <CardProduct key={index + item.name} data={item} />
            ))}
          </Stack>
        </Layout>
      </main>
    </>
  );
}
