import Head from "next/head";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/layout";
import {
  Text,
  Center,
  Button,
  VStack,
  Icon,
  Image,
  HStack,
  Divider,
  Stack,
  useToast,
  Input,
} from "@chakra-ui/react";

import { BsCashCoin } from "react-icons/bs";
import Router from "next/router";
import { ProductList } from "@/data/products";

const inter = Inter({ subsets: ["latin"] });

export default function Payment() {
  let idQuery: number;
  if (Router.query.id) {
    idQuery = Number(Router.query.id);
  }

  const data = ProductList.find((item) => item.id == idQuery);

  let BRL_FORMAT = new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  });

  const toast = useToast({
    description: "Compra fake finalizada",
    status: "success",
    position: "top-right",
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Layout>
          <Center p={8}>
            <Stack gap={10}>
              <Image
                src={data?.url}
                alt="imagem do produto"
                boxSize={"xs"}
                borderRadius={"md"}
                objectFit={"cover"}
              />

              <VStack>
                <Text fontSize={"2xl"} textTransform={"capitalize"}>
                  {data?.name}
                </Text>

                <Text fontSize={"4xl"} as={"b"} textTransform={"capitalize"}>
                  {BRL_FORMAT.format(Number(data?.amount))}
                </Text>
                <Text>{data?.description}</Text>

                <Divider my={4} />

                <Input placeholder="Aplicar cupom" />

                <Button
                  colorScheme="blackAlpha"
                  bg={"black"}
                  onClick={() => {
                    Router.push("/shop");
                    toast();
                  }}
                >
                  Finalizar compra
                </Button>
              </VStack>
            </Stack>
          </Center>
        </Layout>
      </main>
    </>
  );
}
